import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialMigration1700000000000 implements MigrationInterface {
  public async up(_queryRunner: QueryRunner): Promise<void> {
    // This migration will be auto-generated by TypeORM
    // For now, we'll use synchronize in development
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    // Rollback logic
  }
}

